import {build,transform} from 'esbuild';
import {minify} from 'html-minifier-terser';
import {readFile,writeFile,mkdir,rm,cp} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const raiz=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const destino=path.join(raiz,'dist');
await rm(destino,{recursive:true,force:true});await mkdir(path.join(destino,'assets'),{recursive:true});await mkdir(path.join(destino,'html'),{recursive:true});
const config={entryPoints:[path.join(raiz,'js/app.js')],bundle:true,format:'esm',platform:'browser',target:'es2020',write:false,legalComments:'eof'};
const base=(await build({...config,minify:false})).outputFiles[0].contents;
const comprimido=(await build({...config,minify:true})).outputFiles[0].contents;
await writeFile(path.join(destino,'assets/app.min.js'),comprimido);
const css=await readFile(path.join(raiz,'css/estilos.css'),'utf8');
const cssMin=(await transform(css,{loader:'css',minify:true,target:'es2020',legalComments:'eof'})).code;
await writeFile(path.join(destino,'assets/estilos.min.css'),cssMin);
const html=(await readFile(path.join(raiz,'html/index.html'),'utf8')).replace('../css/estilos.css','../assets/estilos.min.css').replace('../js/app.js','../assets/app.min.js');
const htmlMin=await minify(html,{collapseWhitespace:true,conservativeCollapse:true,removeComments:true,removeOptionalTags:false,removeAttributeQuotes:false,removeEmptyAttributes:false});
await writeFile(path.join(destino,'html/index.html'),htmlMin);
const entrada='<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Conecta Solidária</title><script>location.replace("html/index.html"+location.hash)</script></head><body><a href="html/index.html">Abrir Conecta Solidária</a></body></html>';
await writeFile(path.join(destino,'index.html'),entrada);
await cp(path.join(raiz,'imagens'),path.join(destino,'imagens'),{recursive:true});
await cp(path.join(raiz,'js/vendor/DAYJS_LICENSE.txt'),path.join(destino,'DAYJS_LICENSE.txt'));
const registros=[['JavaScript (mesmo bundle antes/depois)',base.length,comprimido.length],['CSS',Buffer.byteLength(css),Buffer.byteLength(cssMin)],['HTML (mesmos caminhos antes/depois)',Buffer.byteLength(html),Buffer.byteLength(htmlMin)]].map(([arquivo,antes,depois])=>({arquivo,antes,depois,reducaoPercentual:(1-depois/antes)*100}));
const antes=registros.reduce((s,r)=>s+r.antes,0),depois=registros.reduce((s,r)=>s+r.depois,0);
const relatorio={ferramentas:{bundler:'esbuild',html:'html-minifier-terser'},criterio:'Comparação em bytes UTF-8, sem gzip/Brotli, imagens e sourcemaps excluídos; JS comparado com o mesmo bundle sem minificação.',registros,total:{antes,depois,reducaoPercentual:(1-depois/antes)*100}};
await writeFile(path.join(raiz,'validacao/minificacao.json'),JSON.stringify(relatorio,null,2));console.log(JSON.stringify(relatorio,null,2));
